name: Archive and Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
    FILENAME: 'Revi-PB-${{ github.ref_name }}.apbx'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update version
        run: |
          $version = "${{ github.ref_name }}"
          $playbookConfPath = "src\playbook.conf"
          $finalizeCMDPath = "src\Executables\FINALIZE.cmd"

          (Get-Content -Path $playbookConfPath) -replace '<Version>.*</Version>', "<Version>$version</Version>" | Set-Content -Path $playbookConfPath

          (Get-Content -Path $finalizeCMDPath) -replace 'set version=.+', "set version=$version" | Set-Content -Path $finalizeCMDPath
        shell: pwsh
        
      - name: Archive content
        run: |
          7z a -pmalte -mhe=on ${{ env.FILENAME }} ./src/*

      - name: Generate SHA256
        run: |
          $hash = (Get-FileHash -Algorithm SHA256 -Path ${{ env.FILENAME }}).Hash
          echo ("HASH=" + $hash) >> $env:GITHUB_ENV

      - name: Release
        if: success()
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.FILENAME }}
          asset_name: ${{ env.FILENAME }}
          tag: ${{ github.ref }}
          release_name: 🌙 ReviOS nightly build
          overwrite: true
          body: |
            ```
            /* 
            * This is an unofficial ReviOS nightly build 
            * 
            * I am not responsible for bricked devices, strained relationships, 
            * thermonuclear war, or you getting fired because the alarm app failed. Please 
            * do some research if you have any concerns about features included in this playbook 
            * before installing it! YOU are choosing to make these modifications, and if 
            * you point the finger at me for messing up your device, I will laugh at you. 
            */
            ```

            ## ⚠️ This is an unofficial ReviOS nightly build which means you'll get no support from the person providing it nor the ReviOS team. ⚠️

            ## 💻 System Requirements

            ReviOS Playbook currently supports ARM64 and AMD64 builds of the following Windows versions:

            - Windows 10 21H2 `19044` (LTSC)
            - Windows 10 22H2 `19045`
            - Windows 11 22H2 `22621`
            - Windows 11 23H2 `22631`
            - Windows 11 24H2 `26100`

            Any other build **is not** supported.

            SHA256: `${{ env.HASH }}`