name: Archive and Release

on:
  push:
    tags:
      - '*'

env:
    SXSC_REPO: 'https://github.com/Atlas-OS/sxsc'
    FILENAME: 'Revi-PB-${{ github.ref_name }}.apbx'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update version
        run: |
          $version = "${{ github.ref_name }}"
          $playbookConfPath = "src\playbook.conf"
          $finalizeCMDPath = "src\Executables\FINALIZE.cmd"

          (Get-Content -Path $playbookConfPath) -replace '<Version>.*</Version>', "<Version>$version</Version>" | Set-Content -Path $playbookConfPath

          (Get-Content -Path $finalizeCMDPath) -replace 'set version=.+', "set version=$version" | Set-Content -Path $finalizeCMDPath
        shell: pwsh

      - name: Git clone sxsc
        run: |
          git clone --depth=1 ${{ env.SXSC_REPO }} sxsc-src

      - name: Build cab
        run: |
          pip install -r requirements.txt | Out-Null
          $systemPackages = "..\src\Executables\CAB\systemPackages.yaml" 
          Copy-Item -Path $systemPackages -Destination "cfg.yaml" -Force | Out-Null
          python sxsc.py
          if ($LASTEXITCODE -ne 0) { exit 1 }
          .\build.bat
          Copy-Item -Path *.cab -Destination "..\src\Executables\CAB" -Force | Out-Null
          .\clean.bat
        working-directory: sxsc-src
      
      - name: Archive content
        run: |
          7z a -pmalte -mhe=on ${{ env.FILENAME }} ./src/*

      - name: Generate SHA256
        run: |
          $hash = (Get-FileHash -Algorithm SHA256 -Path ${{ env.FILENAME }}).Hash
          echo ("HASH=" + $hash) >> $env:GITHUB_ENV

      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.TOKEN }}
          file: ${{ env.FILENAME }}
          asset_name: ${{ env.FILENAME }}
          tag: ${{ github.ref }}
          overwrite: true
          body: |
            Again, this is even more unsupported than the official ReviOS releases.

            Use at your own risk and enjoy!
            
            SHA256: `${{ env.HASH }}`
            