name: Get insider build versions

on:
    workflow_dispatch:

jobs:
  get-versions:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run script and set outputs
      run: |
        python get_versions.py
        echo "CANARY=$(python get_versions.py | awk '{print $1}')" >> $GITHUB_ENV
        echo "DEV=$(python get_versions.py | awk '{print $2}')" >> $GITHUB_ENV
        echo "BETA=$(python get_versions.py | awk '{print $3}')" >> $GITHUB_ENV

    - name: Use versions
      run: |
        echo "Canary version: $CANARY"
        echo "Dev version: $DEV"
        echo "Beta version: $BETA"